### ISSUE TITLE
可以自定义mark的位置和选中日期的颜色吗

### ISSUE THREAD

**Issue by chenyao1208** [OpenFlutter/mini_calendar#6]
大佬，我想自定义mark的位置可以吗，可以自定义选中日期的颜色和形状吗，比如现在默认的选中日期是个矩形的，我想改成圆形的，不知道可以不，希望您可以看到这条

**Comment by yshye** [comment]
> 大佬，我想自定义mark的位置可以吗，可以自定义选中日期的颜色和形状吗，比如现在默认的选中日期是个矩形的，我想改成圆形的，不知道可以不，希望您可以看到这条

可通过自定义日视图来实现你想要的结果
https://github.com/OpenFlutter/mini_calendar/blob/624affc637d290c6b96bacd946d6778c550cecc4/lib/widget/month_widget.dart#L82
可参考默认自定义方法：
https://github.com/OpenFlutter/mini_calendar/blob/624affc637d290c6b96bacd946d6778c550cecc4/lib/handle.dart#L77-L166
