### ISSUE TITLE
可以新建多种不同的marks吗？

### ISSUE THREAD

**Issue by ghost** [OpenFlutter/mini_calendar#7]
你好，我想请问可以比如新建多组标记吗？然后用颜色区分多组标记

**Comment by yshye** [comment]
> 你好，我想请问可以比如新建多组标记吗？然后用颜色区分多组标记

可通过自定义mark进行处理
https://github.com/OpenFlutter/mini_calendar/blob/624affc637d290c6b96bacd946d6778c550cecc4/lib/widget/month_widget.dart#L31-L32

可参考默认构建方法
https://github.com/OpenFlutter/mini_calendar/blob/624affc637d290c6b96bacd946d6778c550cecc4/lib/handle.dart#L29-L38
