### ISSUE TITLE
对于自定义程度高的月视图,如何在自定义头部进行月份切换操作?

### ISSUE THREAD

**Issue by zhechang520** [OpenFlutter/mini_calendar#9]
问题描述： 
由于自定义程度较高, 使用了MonthWidget并完全自定义了月头部,星期头部,日视图等. 但是发现在自定义的月头部中没有提供对应的月份切换操作；
如果使用 MonthPageView 定义, 又没有提供对应的自定义日视图[buildDayItem].
想请问作者,我需要高度自定义的情况下,同时能用到月份切换, 如何配置比较好? 
谢谢~

**Comment by zhechang520** [comment]
仔细梳理了代码, 我尝试将MonthPageView重写了,并在return MonthWidget的时候置入了buildDayItem 示例 可供自定义, 已解决问题~   : )   

感觉可以默认在MonthPageView中提供自定义buildDayItem的话，可扩展性会比较高哈~

**Comment by yshye** [comment]
可考虑添加该功能
